repos:
  - repo: git://github.com/golangci/golangci-lint
    rev: v1.17.1
    hooks:
    - id: golangci-lint
      entry: golangci-lint run
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace